# Generated by Django 2.2.3 on 2019-12-29 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorsapp', '0003_auto_20191229_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='E_mail',
            field=models.CharField(max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='First_Name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Last_Name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Phone_No',
            field=models.CharField(max_length=12, verbose_name='Phone No.'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='No_of_Products',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='No. of Products'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Vendor_Name',
            field=models.CharField(max_length=100, verbose_name='Vendor Name'),
        ),
    ]
