# Generated by Django 2.2.3 on 2019-12-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorsapp', '0005_auto_20191229_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='Product_Name',
        ),
    ]
