# Generated by Django 2.2.3 on 2019-12-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorsapp', '0006_remove_vendor_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='Product_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Product_Price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
