# Generated by Django 2.2.3 on 2019-12-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorsapp', '0007_auto_20191229_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='Product_Price',
        ),
    ]
