# Generated by Django 2.2.3 on 2019-12-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorsapp', '0008_remove_vendor_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='Product_Price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
